name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: gcc:latest

    steps:
      - name: Install dependencies
        run: apt update && apt install -y cmake g++ ninja-build clang-tidy cppcheck

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B build -G "Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
